project:
  type: book
  output-dir: docs

book:
  title: "Practical Python Programming Book Club"
  subtitle: "The R4DS Online Learning Community"
  logo: cover.png
  site-url: https://dabeaz-course.github.io/practical-python/
  repo-url: https://github.com/r4ds
  sharing: [twitter, facebook, linkedin]
  page-footer:
    right: "Illustration by Icons 8 from Ouch!"
  
  chapters:
    - index.qmd
    - part: 01_main.qmd
      chapters: 
      - 01_notes.qmd
      - 01_video.qmd
    - part: 02_main.qmd
      chapters:
      - 02_notes.qmd
      - 02_video.qmd
    - part: 03_main.ipynb
      chapters:
      - 03_notes.ipynb
      - 03_video.ipynb
    - part: examples.md
      chapters:
      - example_quarto.qmd
      - example_python.ipynb
  appendices:
      - how-to.qmd
 
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



